version: '3.1'

services:

  postgresdb:
    image: postgres:12.3
    restart: always
    volumes: 
        - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: sjkd34usjdfbnjs8
      POSTGRES_USER: postgres
      POSTGRES_DB: backend
    ports: 
        - 5432:5432